---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-container
    tier: postgres
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: dmitry
  POSTGRES_DB: test_kuber
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  labels:
    app: redmine-container
    tier: redmine
data:
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: dmitry
  REDMINE_DB_DATABASE: test_kuber
